// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://sqcrqgsmhwbxyswohfvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxY3JxZ3NtaHdieHlzd29oZnZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyMjY2MjMsImV4cCI6MjA5NDgwMjYyM30.ZBXQorhHPROEWW1xw5Em1T0lLCKays59Ta40vXzU6zk";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);